import "./globals.css";
import "./default.css";
import "bootstrap/dist/css/bootstrap.css";

export const metadata = {
	title: "Blogging dev",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
