import "./globals.css";
import "./default.css";
import "bootstrap/dist/css/bootstrap.css";
import Navbar from "./ui/navbar/Navbar";

export const metadata = {
	title: "Blogging dev",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
